fix: rename

diff --git a/compose.yaml b/compose.yaml
--- a/compose.yaml
+++ b/compose.yaml
@@ -1,95 +1,334 @@
-x-customizable-image: &customizable_image
-  # By default the image used only contains the `frappe` and `erpnext` apps.
-  # See https://github.com/frappe/frappe_docker/blob/main/docs/container-setup/02-build-setup.md#define-custom-apps
-  # about using custom images.
-  image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
-  pull_policy: ${PULL_POLICY:-always}
-  restart: ${RESTART_POLICY:-unless-stopped}
-
-x-depends-on-configurator: &depends_on_configurator
-  depends_on:
-    configurator:
-      condition: service_completed_successfully
-
-x-backend-defaults: &backend_defaults
-  <<: [*depends_on_configurator, *customizable_image]
-  volumes:
-    - sites:/home/frappe/frappe-bench/sites
-
 services:
-  configurator:
-    <<: *backend_defaults
+  backend:
+    shm_size: '256mb'
+    depends_on:
+      configurator:
+        condition: service_completed_successfully
+        required: true
+    image: makusu:16
+    networks:
+      default: null
     platform: linux/amd64
+    pull_policy: missing
+    restart: unless-stopped
+    volumes:
+      - type: volume
+        source: sites
+        target: /home/frappe/frappe-bench/sites
+      - type: volume
+        source: chromium
+        target: /home/frappe/frappe-bench/chromium
+
+  configurator:
+    command:
+      - |
+        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
+    depends_on:
+      db:
+        condition: service_healthy
+        required: true
+      redis-cache:
+        condition: service_started
+        required: true
+      redis-queue:
+        condition: service_started
+        required: true
     entrypoint:
       - bash
       - -c
-    # add redis_socketio for backward compatibility
-    command:
-      - >
-        ls -1 apps > sites/apps.txt;
-        bench set-config -g db_host $$DB_HOST;
-        bench set-config -gp db_port $$DB_PORT;
-        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
-        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
-        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
-        bench set-config -gp socketio_port $$SOCKETIO_PORT;
     environment:
-      DB_HOST: ${DB_HOST:-}
-      DB_PORT: ${DB_PORT:-}
-      REDIS_CACHE: ${REDIS_CACHE:-}
-      REDIS_QUEUE: ${REDIS_QUEUE:-}
-      SOCKETIO_PORT: 9000
-    depends_on: {}
-    restart: on-failure
-
-  backend:
-    <<: *backend_defaults
+      DB_HOST: db
+      DB_PORT: "3306"
+      REDIS_CACHE: redis-cache:6379
+      REDIS_QUEUE: redis-queue:6379
+      SOCKETIO_PORT: "9000"
+    image: makusu:16
+    networks:
+      default: null
     platform: linux/amd64
+    pull_policy: missing
+    restart: on-failure
+    volumes:
+      - type: volume
+        source: sites
+        target: /home/frappe/frappe-bench/sites
+
+  create-site:
+    image: makusu:16
+    depends_on:
+      configurator:
+        condition: service_completed_successfully
+      db:
+        condition: service_healthy
+    networks:
+      default: null
+    platform: linux/amd64
+    deploy:
+      restart_policy:
+        condition: none # Ensures this only runs once and doesn't loop if it fails
+    environment:
+      SITE_NAME: "${SITE_NAME}"
+      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
+      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
+    volumes:
+      - type: volume
+        source: sites
+        target: /home/frappe/frappe-bench/sites
+      - type: volume
+        source: chromium
+        target: /home/frappe/frappe-bench/chromium
+    entrypoint:
+      - bash
+      - -c
+    command:
+      - |
+        if [ ! -d "/home/frappe/frappe-bench/sites/$$SITE_NAME" ]; then
+          echo "Site '$$SITE_NAME' does not exist. Bootstrapping now..."
+          
+          bench new-site "$$SITE_NAME" \
+            --mariadb-user-host-login-scope='%' \
+            --db-root-password "$$MYSQL_ROOT_PASSWORD" \
+            --admin-password "$$ADMIN_PASSWORD" \
+            --install-app erpnext \
+            --install-app print_designer \
+            --set-default
+
+          # bench --site "$$SITE_NAME" install-app crm
+          bench --site "$$SITE_NAME" setup-chrome
+          bench --site "$$SITE_NAME" migrate
+          bench --site "$$SITE_NAME" clear-cache
+            
+          echo "Bootstrap complete!"
+        else
+          echo "Site '$$SITE_NAME' already exists. Skipping bootstrap."
+        fi
+
+        # Set pdf_backend to chromium. Guard against failure if already set or Chromium missing.
+        echo "Configuring PDF backend..."
+        bench --site "$$SITE_NAME" set-config pdf_backend chromium || echo "Warning: Failed to set pdf_backend."
+
+        bench --site "$$SITE_NAME" set-config chrome_flags '["--no-sandbox","--disable-dev-shm-usage","--disable-gpu"]'
+
+  db:
+    command:
+      - --character-set-server=utf8mb4
+      - --collation-server=utf8mb4_unicode_ci
+      - --skip-character-set-client-handshake
+      - --skip-innodb-read-only-compressed
+    environment:
+      MARIADB_AUTO_UPGRADE: "1"
+      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
+    healthcheck:
+      test:
+        - CMD
+        - healthcheck.sh
+        - --connect
+        - --innodb_initialized
+      timeout: 5s
+      interval: 5s
+      retries: 5
+      start_period: 5s
+    image: mariadb:11.8
+    networks:
+      default: null
+    restart: unless-stopped
+    volumes:
+      - type: volume
+        source: db-data
+        target: /var/lib/mysql
 
   frontend:
-    <<: *customizable_image
-    platform: linux/amd64
     command:
       - nginx-entrypoint.sh
+    depends_on:
+      backend:
+        condition: service_started
+        required: true
+      websocket:
+        condition: service_started
+        required: true
     environment:
       BACKEND: backend:8000
+      CLIENT_MAX_BODY_SIZE: 50m
+      FRAPPE_SITE_NAME_HEADER: $$host
+      PROXY_READ_TIMEOUT: "120"
       SOCKETIO: websocket:9000
-      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$$host}
-      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
-      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
-      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
-      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
-      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
+      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
+      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
+      UPSTREAM_REAL_IP_RECURSIVE: "off"
+    image: makusu:16
+    networks:
+      default: null
+    platform: linux/amd64
+    ports:
+      - mode: ingress
+        target: 8080
+        published: "8080"
+        protocol: tcp
+    pull_policy: missing
+    restart: unless-stopped
     volumes:
-      - sites:/home/frappe/frappe-bench/sites
+      - type: volume
+        source: sites
+        target: /home/frappe/frappe-bench/sites
+
+  queue-long:
+    shm_size: '256mb'
+    command:
+      - bench
+      - worker
+      - --queue
+      - long,default,short
     depends_on:
-      - backend
-      - websocket
+      configurator:
+        condition: service_completed_successfully
+        required: true
+    image: makusu:16
+    networks:
+      default: null
+    platform: linux/amd64
+    pull_policy: missing
+    restart: unless-stopped
+    volumes:
+      - type: volume
+        source: sites
+        target: /home/frappe/frappe-bench/sites
+      - type: volume
+        source: chromium
+        target: /home/frappe/frappe-bench/chromium
+
+  queue-short:
+    shm_size: '256mb'
+    command:
+      - bench
+      - worker
+      - --queue
+      - short,default
+    depends_on:
+      configurator:
+        condition: service_completed_successfully
+        required: true
+    image: makusu:16
+    networks:
+      default: null
+    platform: linux/amd64
+    pull_policy: missing
+    restart: unless-stopped
+    volumes:
+      - type: volume
+        source: sites
+        target: /home/frappe/frappe-bench/sites
+      - type: volume
+        source: chromium
+        target: /home/frappe/frappe-bench/chromium
+
+  redis-cache:
+    image: redis:6.2-alpine
+    networks:
+      default: null
+    restart: unless-stopped
+
+  redis-queue:
+    image: redis:6.2-alpine
+    networks:
+      default: null
+    restart: unless-stopped
+    volumes:
+      - type: volume
+        source: redis-queue-data
+        target: /data
+
+  scheduler:
+    shm_size: '256mb'
+    command:
+      - bench
+      - schedule
+    depends_on:
+      configurator:
+        condition: service_completed_successfully
+        required: true
+    image: makusu:16
+    networks:
+      default: null
+    platform: linux/amd64
+    pull_policy: missing
+    restart: unless-stopped
+    volumes:
+      - type: volume
+        source: sites
+        target: /home/frappe/frappe-bench/sites
+      - type: volume
+        source: chromium
+        target: /home/frappe/frappe-bench/chromium
 
   websocket:
-    <<: [*depends_on_configurator, *customizable_image]
-    platform: linux/amd64
     command:
       - node
       - /home/frappe/frappe-bench/apps/frappe/socketio.js
+    depends_on:
+      configurator:
+        condition: service_completed_successfully
+        required: true
+    image: makusu:16
+    networks:
+      default: null
+    platform: linux/amd64
+    pull_policy: missing
+    restart: unless-stopped
     volumes:
-      - sites:/home/frappe/frappe-bench/sites
+      - type: volume
+        source: sites
+        target: /home/frappe/frappe-bench/sites
+networks:
+  default:
+    name: makusu-erpnext_default
 
-  queue-short:
-    <<: *backend_defaults
-    platform: linux/amd64
-    command: bench worker --queue short,default
-
-  queue-long:
-    <<: *backend_defaults
-    platform: linux/amd64
-    command: bench worker --queue long,default,short
-
-  scheduler:
-    <<: *backend_defaults
-    platform: linux/amd64
-    command: bench schedule
-
-# ERPNext requires local assets access (Frappe does not)
 volumes:
+  db-data:
+    name: makusu-erpnext_db-data
+    driver: local
+    driver_opts:
+      type: none
+      o: bind
+      device: /mnt/VM/docker/db-data
+  redis-queue-data:
+    name: makusu-erpnext_redis-queue-data
+    driver: local
+    driver_opts:
+      type: none
+      o: bind
+      device: /mnt/VM/docker/redis-queue-data
   sites:
+    name: makusu-erpnext_sites
+    driver: local
+    driver_opts:
+      type: none
+      o: bind
+      device: /mnt/VM/docker/sites
+  chromium:
+    name: makusu-erpnext_chromium
+    driver: local
+    driver_opts:
+      type: none
+      o: bind
+      device: /mnt/VM/docker/chromium
+
+x-backend-defaults:
+  depends_on:
+    configurator:
+      condition: service_completed_successfully
+  image: makusu:16
+  pull_policy: missing
+  restart: unless-stopped
+  volumes:
+    - sites:/home/frappe/frappe-bench/sites
+
+x-customizable-image:
+  image: makusu:16
+  pull_policy: missing
+  restart: unless-stopped
+
+x-depends-on-configurator:
+  depends_on:
+    configurator:
+      condition: service_completed_successfully
